export const PATH = {
  ADMIN_DASHBOARD: 'AdminDashboardScreen',
  ADMIN_VOTE_EDIT: 'AdminVoteEditScreen',
  ADMIN_VOTE_RESULT: 'AdminVoteResultScreen',
  ADMIN_VOTE_STATUS: 'AdminVoteStatusScreen',
  ADMIN_HOME: 'AdminHomeScreen',
  LOGIN: 'LoginScreen',
  HOME: 'HomeScreen',
  JOIN: 'JoinScreen',
  JOIN_COMPLETE: 'JoinCompleteScreen',
  JOIN_LOADING: 'JoinLoadingScreen',
  NOTICE: 'NoticeScreen',
  NOTICE_CONTENT: 'NoticeContentScreen',
  NOTICE_CREATE: 'NoticeCreateScreen',
  VOTE: 'VoteScreen',
  VOTE_COMPLETE: 'VoteCompleteScreen',
  VOTE_CREATE: 'VoteCreateScreen',
  VOTE_CREATE_COMPLETE: 'VoteCreateCompleteScreen',
  VOTE_EDIT: 'VoteEditScreen',
  VOTE_PROMISE: 'VotePromiseScreen',
  VOTE_RESULT: 'VoteResultScreen',
  VOTE_RESULT_CONTENT: 'VoteResultContentScreen',
} as const;

export const RAW_PATH = {
  HOME: '/',
  AUTH: '/auth',
  SIGNUP: '/signup',
  SIGNUP_LOADING: '/signup-loading',
  SIGNUP_COMPLETE: '/signup-complete',
};
