export const PATH = {
  ADMIN_DASHBOARD: 'AdminDashboardScreen',
  ADMIN_VOTE_EDIT: 'AdminVoteEditScreen',
  ADMIN_VOTE_RESULT: 'AdminVoteResultScreen',
  ADMIN_VOTE_STATUS: 'AdminVoteStatusScreen',
  ADMIN_HOME: 'AdminHomeScreen',
  LOGIN: 'LoginScreen',
  HOME: 'HomeScreen',
  NOTICE: 'NoticeScreen',
  NOTICE_CONTENT: 'NoticeContentScreen',
  NOTICE_CREATE: 'NoticeCreateScreen',
  VOTE: 'VoteScreen',
  VOTE_COMPLETE: 'VoteCompleteScreen',
  VOTE_CREATE: 'VoteCreateScreen',
  VOTE_CREATE_LOADING: 'VoteCreateLoadingScreen',
  VOTE_CREATE_COMPLETE: 'VoteCreateCompleteScreen',
  VOTE_EDIT: 'VoteEditScreen',
  VOTE_PROMISE: 'VotePromiseScreen',
  VOTE_RESULT: 'VoteResultScreen',
  VOTE_RESULT_CONTENT: 'VoteResultContentScreen',
  USER: 'UserScreen',
} as const;

export const RAW_PATH = {
  HOME: '/',
  AUTH: '/auth/kakao',
  SIGNUP: '/signup',
  SIGNUP_LOADING: '/signup-loading',
  SIGNUP_COMPLETE: '/signup-complete',
};
