export const REQUEST = {
  USER: '/api/users/',
  LOGIN: '/auth/kakao',
  JOIN: '/auth/kakao/signup',
  REFRESH: '/auth/refresh',
  ELECTION: '/api/elections/',
  ELECTION_ALL: '/api/elections/all',
  ELECTION_STATUS: '/api/elections/status',
  NOTICE: '/api/notices/',
  NOTICE_CAMPUS: '/api/notices/notices/campus/',
  CANDIDATE: '/api/candidates/',
  CANDIDATE_ALL: '/api/candidates/all/',
  NOMINEE_POST: '/api/nominees/',
  NOMINEE: '/api/nominees/{candidateId}/all',
  PLEDGE: '/api/pledges/{candidateId}/all',
  PLEDGE_POST: '/api/pledges/',
};
